name = "lnncm2b"
main = "_worker.js"
compatibility_date = "2025-11-04"

keep_vars = true
# 环境变量
[vars]
ADMIN = "liwanxi521"	
#✅	面板登录密码
KEY = "n"
#❌	快速订阅密钥，访问/CMLiussss即可快读订阅。
#HOST = "edt-pages.github.io"
#❌	强制固定伪装域名
UUID = "63c64f52-4aa6-45ff-916c-98ab286d8d59"
#❌	强制固定UUID
#PATH = "/"
#❌	强制固定路径
PROXYIP = "us.cmliussss.net"
#❌	更换默认内置PROXYIP
URL = "https://nuo.lnn.ink/"	
#❌	主页反代伪装(乱设容易触发反诈，反代被墙的网站会加速域名被墙)
#GO2SOCKS5 = "socks5://192.252.209.155:14455#OTC-CA
#socks5://104.37.135.145:4145#OTC-US
#socks5://184.185.2.12:4145#OTC-US
#socks5://98.191.0.47:4145#OTC-US
#socks5://74.119.147.209:4145#OTC-US
#socks5://192.252.208.70:14282#OTC-CA
#socks5://24.249.199.4:4145#OTC-US
#socks5://87.236.38.23:1080#OTC-CY
#socks5://138.68.60.8:1080#OTC-US
#socks5://142.54.229.249:4145#OTC-US
#socks5://199.102.104.70:4145#OTC-US
#socks5://192.252.220.89:4145#OTC-US
#socks5://184.178.172.26:4145#OTC-US
#socks5://98.181.137.83:4145#OTC-US
#socks5://68.71.240.210:4145#OTC-US
#socks5://142.54.237.34:4145#OTC-US
#socks5://199.102.107.145:4145#OTC-US
#socks5://68.71.243.14:4145#OTC-US
#socks5://98.191.0.37:4145#OTC-US
#socks5://184.181.217.194:4145#OTC-US
#socks5://72.195.34.41:4145#OTC-US
#socks5://98.188.47.132:4145#OTC-US
#socks5://72.223.188.92:4145#OTC-US
#socks5://142.54.239.1:4145#OTC-US
#socks5://142.54.236.97:4145#OTC-US
#socks5://199.116.114.11:4145#OTC-US"	
#❌	设置SOCKS5或HTTP变量之后，可设置强制使用socks5访问名单(设置为*可作为全局代理)SOCK5 API https://socks5.qqqqqq.tk/	
#❌	设置SOCKS5或HTTP变量之后，可设置强制使用socks5访问名单(设置为*可作为全局代理)
# KV 命名空间绑定
[[kv_namespaces]]
binding = "KV"
id = "e7052ace88174d1e979c32c368991f19"
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1





