name = "lnnl"
main = "_worker.js"
compatibility_date = "2025-11-04"

keep_vars = true
# 环境变量
[vars]
ADMIN = "liwanxi521"	
#✅	面板登录密码
KEY = "n"
#❌	快速订阅密钥，访问/CMLiussss即可快读订阅。
#HOST = "edt-pages.github.io"
#❌	强制固定伪装域名
#UUID = "90cd4a77-141a-43c9-991b-08263cfe9c10"
#❌	强制固定UUID
#PATH = "/"
#❌	强制固定路径
PROXYIP = "us.cmliussss.net"
#❌	更换默认内置PROXYIP
URL = "https://nuo.lnn.ink/"	
#❌	主页反代伪装(乱设容易触发反诈，反代被墙的网站会加速域名被墙)
#GO2SOCKS5 = "blog.cmliussss.com,*.ip111.cn,*google.com"	
#❌	设置SOCKS5或HTTP变量之后，可设置强制使用socks5访问名单(设置为*可作为全局代理)
# KV 命名空间绑定
[[kv_namespaces]]
binding = "KV"
id = "e7052ace88174d1e979c32c368991f19"


