name = "lnncmzx"
main = "_worker.js"
compatibility_date = "2025-11-04"

keep_vars = true
# 环境变量
[vars]
ADMIN = "liwanxi521"
PROXYIP = "us.cmliussss.net"
KEY = "n"
# KV 命名空间绑定
[[kv_namespaces]]
binding = "KV"
id = "aae6f52499414b2ba2a80c3ae3f535c2"
