name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"   # 每天自动同步
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync upstream changes
        id: sync
        uses: aormsby/branch-sync-with-upstream-action@v3.4
        with:
          upstream_sync_repo: cmliu/edgetunnel
          upstream_sync_branch: 1.0
          target_sync_branch: 1.0
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] GitHub 自动暂停了自动同步（通常是因为上游 workflow 文件变更）。"
          echo "请手动执行一次 Sync Fork，然后自动同步将恢复正常。"
          exit 1
